
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Enables blur on the live meter window.
 * 
 * # Arguments
 * 
 * * `app` - A handle to the Tauri application instance.
 */
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
/**
 * Disables blur on the live meter window.
 * 
 * # Arguments
 * 
 * * `app` - A handle to the Tauri application instance.
 */
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
/**
 * Resets the encounter.
 * 
 * # Arguments
 * 
 * * `state_manager` - The state manager.
 * 
 * # Returns
 * 
 * * `Result<(), String>` - An empty result.
 */
async resetEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles pausing the encounter.
 * 
 * # Arguments
 * 
 * * `state_manager` - The state manager.
 * 
 * # Returns
 * 
 * * `Result<(), String>` - An empty result.
 */
async togglePauseEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pause_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTrainingDummy(monsterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_training_dummy", { monsterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTrainingDummy() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_training_dummy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAndApplyMonitorRuntimeSnapshot(snapshot: MonitorRuntimeSnapshot) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_and_apply_monitor_runtime_snapshot", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of recent encounters.
 * 
 * # Arguments
 * 
 * * `limit` - The maximum number of encounters to return.
 * * `offset` - The number of encounters to skip.
 * 
 * # Returns
 * 
 * * `Result<RecentEncountersResult, String>` - A list of recent encounters.
 */
async getRecentEncounters(limit: number, offset: number) : Promise<Result<RecentEncountersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_encounters", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of unique scene names.
 * 
 * # Returns
 * 
 * * `Result<SceneNamesResult, String>` - A list of unique scene names.
 */
async getUniqueSceneNames() : Promise<Result<SceneNamesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_scene_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of unique boss names.
 * 
 * # Returns
 * 
 * * `Result<BossNamesResult, String>` - A list of unique boss names.
 */
async getUniqueBossNames() : Promise<Result<BossNamesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_boss_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of player names filtered by a prefix.
 * 
 * This will return up to 5 matching player names (to keep the UI responsive).
 * 
 * # Arguments
 * 
 * * `prefix` - The prefix to filter by.
 * 
 * # Returns
 * 
 * * `Result<PlayerNamesResult, String>` - A list of player names.
 */
async getPlayerNamesFiltered(prefix: string) : Promise<Result<PlayerNamesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_names_filtered", { prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of recent encounters filtered by the given criteria.
 * 
 * # Arguments
 * 
 * * `limit` - The maximum number of encounters to return.
 * * `offset` - The number of encounters to skip.
 * * `filters` - The filters to apply.
 * 
 * # Returns
 * 
 * * `Result<RecentEncountersResult, String>` - A list of recent encounters.
 */
async getRecentEncountersFiltered(limit: number, offset: number, filters: EncounterFiltersDto | null) : Promise<Result<RecentEncountersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_encounters_filtered", { limit, offset, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets an encounter by its ID.
 * 
 * # Arguments
 * 
 * * `encounter_id` - The ID of the encounter.
 * 
 * # Returns
 * 
 * * `Result<EncounterSummaryDto, String>` - The encounter summary.
 */
async getEncounterById(encounterId: number) : Promise<Result<EncounterSummaryDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_by_id", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets raw actor entities for a historical encounter.
 */
async getEncounterEntitiesRaw(encounterId: number) : Promise<Result<HistoryEntityData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_entities_raw", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets compact historical entities without modifier ledgers for fast overview/skill pages.
 */
async getEncounterEntitiesCompactRaw(encounterId: number) : Promise<Result<HistoryEntityData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_entities_compact_raw", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets compact historical entities plus full per-target skill maps for target drill-down pages.
 */
async getEncounterEntitiesTargetDetailsRaw(encounterId: number) : Promise<Result<HistoryEntityData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_entities_target_details_raw", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets modifier details scoped to one historical player plus hosted external state.
 */
async getEncounterModifierEntitiesRaw(encounterId: number, entityUid: number) : Promise<Result<HistoryEntityData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_modifier_entities_raw", { encounterId, entityUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an encounter by its ID.
 * 
 * # Arguments
 * 
 * * `encounter_id` - The ID of the encounter to delete.
 * 
 * # Returns
 * 
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async deleteEncounter(encounterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounter", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple encounters by ID.
 * 
 * # Arguments
 * 
 * * `ids` - The IDs of the encounters to delete.
 * 
 * # Returns
 * 
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async deleteEncounters(ids: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounters", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the favorite status of an encounter.
 * 
 * # Arguments
 * 
 * * `id` - The ID of the encounter.
 * * `is_favorite` - The new favorite status.
 * 
 * # Returns
 * 
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async toggleFavoriteEncounter(id: number, isFavorite: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_favorite_encounter", { id, isFavorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A Tauri command to get a list of recent players.
 * 
 * # Arguments
 * 
 * * `limit` - The maximum number of players to return.
 * 
 * # Returns
 * 
 * * `Result<Vec<(i64, String)>, String>` - A list of recent players.
 */
async getRecentPlayersCommand(limit: number) : Promise<Result<([number, string])[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_players_command", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A Tauri command to get the name of a player by their UID.
 * 
 * # Arguments
 * 
 * * `uid` - The UID of the player.
 * 
 * # Returns
 * 
 * * `Result<Option<String>, String>` - The name of the player, or `None` if not found.
 */
async getPlayerNameCommand(uid: number) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_name_command", { uid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePacketCaptureSettings(method: string, npcapDevice: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_packet_capture_settings", { method, npcapDevice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readCustomDefinitions() : Promise<Result<CustomDefinitionsFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_custom_definitions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeCustomDefinitions(payload: CustomDefinitionsFile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_custom_definitions", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readCustomTriggers() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_custom_triggers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeCustomTriggers(payload: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_custom_triggers", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readEventLoggerBuffer() : Promise<EventLoggerBatchPayload> {
    return await TAURI_INVOKE("read_event_logger_buffer");
},
async clearEventLoggerBuffer() : Promise<void> {
    await TAURI_INVOKE("clear_event_logger_buffer");
},
async showEventLoggerWindow(alwaysOnTop: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_event_logger_window", { alwaysOnTop }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideEventLoggerWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_event_logger_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleEventLoggerWindow(alwaysOnTop: boolean | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_event_logger_window", { alwaysOnTop }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEventLoggerWindowAlwaysOnTop(alwaysOnTop: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_event_logger_window_always_on_top", { alwaysOnTop }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventLoggerSessionDirectory() : Promise<Result<EventLoggerSessionDirectoryPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_event_logger_session_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEventLoggerSaveDirectory(directory: string | null) : Promise<Result<EventLoggerSessionDirectoryPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_event_logger_save_directory", { directory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventLoggerFileStorageSettings() : Promise<Result<EventLoggerFileStoragePayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_event_logger_file_storage_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEventLoggerFileStorageSettings(storeLogFiles: boolean, includeRepeatedSnapshotRows: boolean, deleteOlderThanDays: number | null, captureCensusEnabled: boolean, attributionCensusEnabled: boolean) : Promise<Result<EventLoggerFileStoragePayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_event_logger_file_storage_settings", { storeLogFiles, includeRepeatedSnapshotRows, deleteOlderThanDays, captureCensusEnabled, attributionCensusEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportEventLoggerSession() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_event_logger_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openEventLoggerSessionDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_event_logger_session_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNetworkDevices() : Promise<Result<Device[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_network_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkNpcapStatus() : Promise<boolean> {
    return await TAURI_INVOKE("check_npcap_status");
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a debug ZIP containing the most recent application log file and returns the path.
 * 
 * If `destination_path` is provided, the ZIP is written there. Otherwise it is created
 * in the app log directory.
 */
async createDiagnosticsBundle(destinationPath: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_diagnostics_bundle", { destinationPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkGpuSupport() : Promise<GpuSupport> {
    return await TAURI_INVOKE("check_gpu_support");
},
async getLatestModules() : Promise<Result<ModuleInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_modules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeLatestModules(targetAttributes: number[], excludeAttributes: number[], minTotalValue: number | null, minAttrRequirements: Partial<{ [key in number]: number }> | null, useGpu: boolean | null, combinationSize: number | null) : Promise<Result<ModuleSolution[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_latest_modules", { targetAttributes, excludeAttributes, minTotalValue, minAttrRequirements, useGpu, combinationSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initializeTranslationRuntimeFiles() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_translation_runtime_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranslationRuntimeStatus() : Promise<Result<TranslationRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_translation_runtime_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairRuntimeLocaleFolder() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_runtime_locale_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openTranslationDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_translation_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshTranslationRuntimeData() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_translation_runtime_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTranslationRuntimeFiles() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_translation_runtime_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readTranslationRuntimeFile(relativePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_translation_runtime_file", { relativePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTranslationRuntimeFile(relativePath: string, contents: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_translation_runtime_file", { relativePath, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTranslationRuntimeLocaleFile(relativePath: string, locale: string, contents: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_translation_runtime_locale_file", { relativePath, locale, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTranslationRuntimeLocalePatch(relativePath: string, locale: string, patchContents: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_translation_runtime_locale_patch", { relativePath, locale, patchContents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateUiTranslationScaffold(relativePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_ui_translation_scaffold", { relativePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateAllUiTranslationScaffolds() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_all_ui_translation_scaffolds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleGameOverlayWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_game_overlay_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHideMainWindowToTray(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hide_main_window_to_tray", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleGameOverlayEditMode() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_game_overlay_edit_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncMonsterOverlayWindowToGameOverlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_monster_overlay_window_to_game_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveBuffState = { buffUuid: number; baseId: number; buffLevel: number | null; partId: number | null; count: number | null; fightSourceType: number | null; sourceConfigId: number | null; layer: number; durationMs: number; createTimeMs: number; receivedTimeMs: number; hostUid: number; sourceUid: number }
export type ActiveEffectBuffState = { effectSourceBuffId: number; observedBuffId: number; buffLevel: number | null; partId: number | null; count: number | null; fightSourceType: number | null; sourceConfigId: number | null; layer: number; durationMs: number; createTimeMs: number; receivedTimeMs: number; hostUid: number; sourceUid: number }
export type ActiveEffectSourceState = { sourceId: string; runtimeSource: string; sourceEntityId: number | null; nodeId: number | null; nodeLevel: number | null; slot: number | null }
export type ActiveFactorBuffState = { factorBuffId: number; observedBuffId: number; buffLevel: number | null; partId: number | null; count: number | null; fightSourceType: number | null; sourceConfigId: number | null; layer: number; durationMs: number; createTimeMs: number; receivedTimeMs: number; hostUid: number; sourceUid: number }
export type ActiveFactorItemState = { factorBuffId: number; itemConfigId: number; itemUuid: number | null; packageKey: number; packageType: number | null; grade: number | null; familyId: number | null; runtimeSource: string; selectorPath: string | null; selectorSignature: string | null; selectorOffset: number | null }
export type ActivePassiveSkillState = { passiveUuid: number | null; targetUid: number | null; stageBeginTime: number | null; beginTime: number | null; stagePlayNum: number | null; skillId: number | null; skillLevel: number | null; skillStage: number | null; runtimeSource: string }
export type ActiveProfessionSkillState = { skillId: number; baseSkillId: number | null; skillLevelId: number | null; level: number | null; remodelLevel: number | null; slot: number | null; equipped: boolean | null; sourceKind: string; replaceSkillIds: number[]; runtimeSource: string }
export type ActiveProfessionTalentState = { professionId: number; talentNodeId: number; usedTalentPoints: number | null; talentStageCfgId: number | null; runtimeSource: string }
export type AltFreezeConfig = { conditionBuffId: number; freezeDurationMs: number }
export type AttrModifier = { attrId: number; basisPointsPerUnit?: number; maxReductionBasisPoints: number }
/**
 * The result of a query for boss names.
 */
export type BossNamesResult = { 
/**
 * A list of boss names.
 */
names: string[] }
/**
 * A summary of a boss.
 */
export type BossSummaryDto = { 
/**
 * The name of the monster.
 */
monsterName: string; 
/**
 * The maximum HP of the monster.
 */
maxHp: number | null; 
/**
 * Whether the boss was defeated.
 */
isDefeated: boolean }
export type CounterAction = "reset" | "freeze" | "resetAndFreeze" | "resetAndFreezeKeepCounting" | "resetAndStartCount" | "startCount" | "noOp"
export type CounterRule = { ruleId: number; sources: CounterSource[]; effectSlots: EffectSlotConfig[] }
export type CounterSource = { damageBySkillKey: { skillKeys: number[]; increment: number; hitsRequired?: number | null } } | { damageBySkillKeyOnce: { skillKeys: number[]; increment: number } } | { damageBySkillKeySelfTarget: { skillKeys: number[]; increment: number; hitsRequired?: number | null } } | { anyDamage: { increment: number; hitsRequired?: number | null } } | { damageTaken: { skillKeys?: number[] | null; increment: number; hitsRequired?: number | null } } | { fightResourceSpent: { resourceId: number; unitsRequired: number; increment: number } } | { buffDurationTick: { buffId: number; tickIntervalMs: number; increment: number; attrCondition?: TickAttrCondition | null } } | { skillCast: { skillBaseIds: number[]; increment: number } } | { skillDurationTick: { skillBaseId: number; tickIntervalMs: number; increment: number } } | { skillCastComplete: { skillBaseIds: number[]; increment: number } } | { movementDistance: { buffId: number; attrId: number; metersRequired: number; increment: number } }
export type CustomDefinitionEntry = { uid: number; type: string; name: string; shortName: string | null; notes: string | null; icon: string | null; color: string | null }
export type CustomDefinitionsFile = { version: number; definitions: CustomDefinitionEntry[] }
/**
 * A single damage event recorded in the 2s sliding window used for death replay.
 */
export type DamageSnapshot = { timestampMs: number; attackerUid: number; attackerMonsterTypeId: number | null; skillKey: number; value: number }
export type DeathRecord = { victimUid: number; deathTimestampMs: number; recentDamages: DamageSnapshot[] }
export type Device = { name: string; description: string | null }
export type EffectSlotConfig = { slotId: number; threshold: number | null; resetBuffId: number; resetSourceConfigId?: number | null; onBuffAdd?: CounterAction; onBuffChange?: CounterAction; onBuffRemove?: CounterAction; freezeDurationMs?: number | null; onFreezeExpire?: CounterAction; altFreeze?: AltFreezeConfig | null; thresholdModifier?: AttrModifier | null; freezeDurationModifier?: AttrModifier | null; resetSkillKeys?: number[] | null; onResetSkill?: CounterAction }
/**
 * Filters for querying encounters.
 */
export type EncounterFiltersDto = { 
/**
 * A list of boss names to filter by.
 */
bossNames: string[] | null; 
/**
 * A list of encounter names to filter by.
 */
encounterNames: string[] | null; 
/**
 * A player name to filter by.
 */
playerName: string | null; 
/**
 * A list of player names to filter by.
 */
playerNames: string[] | null; 
/**
 * The start date to filter by in milliseconds since the Unix epoch.
 */
dateFromMs: number | null; 
/**
 * The end date to filter by in milliseconds since the Unix epoch.
 */
dateToMs: number | null; 
/**
 * Whether to filter by favorite encounters.
 */
isFavorite: boolean | null }
/**
 * A summary of an encounter.
 */
export type EncounterSummaryDto = { 
/**
 * The ID of the encounter.
 */
id: number; 
/**
 * The start time of the encounter in milliseconds since the Unix epoch.
 */
startedAtMs: number; 
/**
 * The end time of the encounter in milliseconds since the Unix epoch.
 */
endedAtMs: number | null; 
/**
 * The total damage dealt in the encounter.
 */
totalDmg: number; 
/**
 * The total healing done in the encounter.
 */
totalHeal: number; 
/**
 * The ID of the scene where the encounter took place.
 */
sceneId: number | null; 
/**
 * The name of the scene where the encounter took place.
 */
sceneName: string | null; 
/**
 * The duration of the encounter in seconds.
 */
duration: number; 
/**
 * The accumulated active combat duration in seconds.
 */
activeCombatDuration: number | null; 
/**
 * The UID of the local player for this encounter.
 */
localPlayerId: number | null; 
/**
 * A list of bosses in the encounter.
 */
bosses: BossSummaryDto[]; 
/**
 * A list of players in the encounter.
 */
players: PlayerSummaryDto[]; 
/**
 * The encounter ID on the remote website/server after successful upload.
 */
remoteEncounterId: number | null; 
/**
 * Whether the encounter is favorited.
 */
isFavorite: boolean }
export type EventLoggerBatchPayload = { entries: EventLoggerEntry[] }
export type EventLoggerEntry = { tsMs: number; category: string; action: string; uid: number | null; targetUid: number | null; sourceUid: number | null; sourceLabel: string | null; targetLabel: string | null; nameHint: string | null; summary: string | null; stacks: number | null; durationMs: number | null; remainingMs: number | null; value: string | null; raw: string }
export type EventLoggerFileStoragePayload = { configuredDirectory: string | null; resolvedDirectory: string; usingDefault: boolean; storeLogFiles: boolean; includeRepeatedSnapshotRows: boolean; deleteOlderThanDays: number | null; captureCensusEnabled: boolean; attributionCensusEnabled: boolean }
export type EventLoggerSessionDirectoryPayload = { configuredDirectory: string | null; resolvedDirectory: string; usingDefault: boolean }
export type GpuSupport = { cuda_available: boolean; opencl_available: boolean }
export type HistoryEntityData = { uid: number; name: string; classId: number; classSpec: number; className: string; classSpecName: string; abilityScore: number; seasonStrength: number; damage: RawCombatStats; damageBossOnly: RawCombatStats; healing: RawCombatStats; taken: RawCombatStats; dmgSkills: Partial<{ [key in number]: RawSkillStats }>; healSkills: Partial<{ [key in number]: RawSkillStats }>; takenSkills: Partial<{ [key in number]: RawSkillStats }>; activeBuffs: ActiveBuffState[]; activeFactorBuffs: ActiveFactorBuffState[]; activeEffectBuffs: ActiveEffectBuffState[]; modifierWindows: ModifierWindowState[]; modifierHitBuckets: ModifierHitBucketState[]; modifierReplayHits: ModifierReplayHitState[]; skillCastEvents: SkillCastEventState[]; skillCooldownEvents: SkillCooldownEventState[]; activeEffectSources: ActiveEffectSourceState[]; activeFactorItems: ActiveFactorItemState[]; activePassiveSkills: ActivePassiveSkillState[]; activeProfessionSkills: ActiveProfessionSkillState[]; activeProfessionTalents: ActiveProfessionTalentState[]; modifierSourceActors?: ModifierSourceActorState[]; dmgPerTarget: PerTargetStats[]; healPerTarget: PerTargetStats[]; deaths: DeathRecord[] }
export type LiveRuntimeSnapshot = { eventUpdateRateMs: number; autoClearOnSceneChange?: boolean; modifierReportsEnabled: boolean; modifierReportsOptInVersion: string | null }
export type ModifierHitBucketState = { modifierBuffUuid: number; modifierBaseId: number; modifierBuffLevel: number | null; modifierPartId: number | null; modifierCount: number | null; modifierFightSourceType: number | null; modifierSourceConfigId: number | null; modifierLayer: number; modifierDurationMs: number; modifierStartTimeMs: number; modifierEndTimeMs: number | null; modifierHostUid: number; modifierSourceUid: number; skillKey: number; damageId: number; ownerId: number; ownerLevel: number | null; hitEventId: number | null; damageSource: number | null; property: number | null; damageMode: number | null; attackerUid: number; originalAttackerUid: number; topSummonerUid: number | null; targetUid: number; targetMonsterTypeId: number | null; isHeal: boolean; hits: number; totalValue: number; effectiveTotalValue: number; critHits: number; critTotalValue: number; luckyHits: number; luckyTotalValue: number; hpLossTotal: number; shieldLossTotal: number; firstHitTimeMs: number; lastHitTimeMs: number }
export type ModifierReplayAttrState = { attrId: number; valueInt: number | null; valueFloat: number | null; valueBool: boolean | null }
export type ModifierReplayHitState = { timestampMs: number; skillKey: number; damageId: number; ownerId: number; ownerLevel: number | null; hitEventId: number | null; damageSource: number | null; property: number | null; damageMode: number | null; attackerUid: number; originalAttackerUid: number; topSummonerUid: number | null; targetUid: number; targetMonsterTypeId: number | null; isHeal: boolean; isCrit: boolean; isLucky: boolean; value: number; effectiveValue: number; hpLossValue: number; shieldLossValue: number; activeModifiers: ModifierReplaySourceState[]; attackerAttrs: ModifierReplayAttrState[]; targetAttrs: ModifierReplayAttrState[] }
export type ModifierReplaySourceState = { modifierBaseId: number; modifierSourceConfigId: number | null; modifierBuffLevel: number | null; modifierCount: number | null; modifierLayer: number; modifierHostUid: number; modifierSourceUid: number }
export type ModifierSourceActorState = { uid: number; name: string; entityType: string; ownerUid: number | null; ownerName: string | null; sourceConfigIds: number[]; baseIds: number[] }
export type ModifierWindowState = { buffUuid: number; baseId: number; buffLevel: number | null; partId: number | null; count: number | null; fightSourceType: number | null; sourceConfigId: number | null; layer: number; durationMs: number; startTimeMs: number; endTimeMs: number | null; hostUid: number; sourceUid: number }
export type ModuleInfo = { name: string; config_id: number; uuid: number; quality: number; parts: ModulePart[] }
export type ModulePart = { id: number; name: string; value: number }
export type ModuleSolution = { modules: ModuleInfo[]; score: number; attr_breakdown: Partial<{ [key in string]: number }> }
export type MonitorRuntimeSnapshot = { live: LiveRuntimeSnapshot; skill: SkillRuntimeSnapshot; monster: MonsterRuntimeSnapshot }
export type MonsterRuntimeSnapshot = { enabled: boolean; globalIds: number[]; selfAppliedIds: number[] }
export type PerTargetStats = { targetUid: number; targetName: string; totalValue: number; damage: RawCombatStats; skills: Partial<{ [key in number]: RawSkillStats }> }
/**
 * The result of a query for player names.
 */
export type PlayerNamesResult = { 
/**
 * A list of player names.
 */
names: string[] }
/**
 * A summary of a player in an encounter.
 */
export type PlayerSummaryDto = { 
/**
 * The player UID.
 */
uid: number; 
/**
 * The player name.
 */
name: string; 
/**
 * The class ID of the player.
 */
classId: number; 
/**
 * The class specialization enum value of the player.
 */
classSpec: number; 
/**
 * The class specialization name of the player.
 */
classSpecName: string }
export type RawCombatStats = { total: number; effectiveTotal: number; hits: number; critHits: number; critTotal: number; luckyHits: number; luckyTotal: number }
export type RawSkillStats = { totalValue: number; effectiveTotalValue: number; hits: number; critHits: number; critTotalValue: number; luckyHits: number; luckyTotalValue: number; property: number | null; damageMode: number | null }
/**
 * The result of a query for recent encounters.
 */
export type RecentEncountersResult = { 
/**
 * The rows of encounter summaries.
 */
rows: EncounterSummaryDto[]; 
/**
 * The total number of encounters.
 */
totalCount: number }
/**
 * The result of a query for scene names.
 */
export type SceneNamesResult = { 
/**
 * A list of scene names.
 */
names: string[] }
export type SkillCastEventState = { timestampMs: number; skillId: number; source: string }
export type SkillCooldownEventState = { timestampMs: number; skillLevelId: number; skillId: number; beginTime: number; duration: number; calculatedDuration: number; cdAccelerateRate: number; skillCdType: number; validCdTime: number; attrSkillCd: number; attrSkillCdPct: number; attrCdAcceleratePct: number }
export type SkillRuntimeSnapshot = { enabled: boolean; monitoredSkillIds: number[]; monitoredBuffIds: number[]; monitorAllBuff: boolean; monitoredPanelAttrIds: number[]; buffCounterRules: CounterRule[] }
export type TickAttrCondition = { attrId: number; requiredValue: number }
export type TranslationRuntimeStatus = { runtimeDir: string; runtimeExists: boolean; runtimeManifestExists: boolean; sourceDir: string | null; sourceExists: boolean; sourceManifestExists: boolean; sourceCandidates: string[]; sourceError: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

