// This file is generated by `npm run bindings`.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async pullLiveWindowFrame(request: LiveWindowFrameRequest) : Promise<Result<LiveWindowFrame, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_live_window_frame", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pullHudFrame(request: HudFrameRequest) : Promise<Result<HudFrame, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_hud_frame", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLivePullActive(window: LivePullWindow, active: boolean) : Promise<void> {
    await TAURI_INVOKE("set_live_pull_active", { window, active });
},
/**
 * One-shot status read for the main-window settings preview.
 */
async getLiveStatus() : Promise<Result<LiveStatusPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_live_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bootstrap for the `live-scene` topic. `main`-only: drives the daily-scene
 * auto-hide logic for the unified HUD overlay without
 * subscribing to the far heavier `live-combat` cadence.
 */
async getLiveScene() : Promise<Result<LiveScenePayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_live_scene") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async migrateHudLayout(complete: boolean) : Promise<Result<HudLayoutMigration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_hud_layout", { complete }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
async resetEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePauseEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pause_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTrainingDummy() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_training_dummy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTrainingDummy() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_training_dummy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAndApplyMonitorRuntimeSnapshot(snapshot: MonitorRuntimeSnapshot) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_and_apply_monitor_runtime_snapshot", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUniqueSceneIds() : Promise<Result<SceneIdsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_scene_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUniqueBossMonsterIds() : Promise<Result<BossMonsterIdsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_boss_monster_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayerNamesFiltered(prefix: string) : Promise<Result<PlayerNamesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_names_filtered", { prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecentEncountersFiltered(limit: number, offset: number, filters: EncounterFiltersDto | null) : Promise<Result<RecentEncountersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_encounters_filtered", { limit, offset, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEncounterDetail(encounterId: number) : Promise<Result<EncounterDetailData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_detail", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEncounterRange(encounterId: number, startMs: number, endMs: number) : Promise<Result<EncounterRangeData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_range", { encounterId, startMs, endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEncounter(encounterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounter", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEncounters(ids: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounters", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleFavoriteEncounter(id: number, isFavorite: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_favorite_encounter", { id, isFavorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePacketCaptureSettings(method: string, npcapDevice: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_packet_capture_settings", { method, npcapDevice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Best-effort backup of the persisted settings stores before running a
 * one-time frontend migration. Copies every RuneStore JSON file into
 * `tauri-plugin-svelte/backup-v1/` without replacing the first snapshot.
 */
async backupSettingsStores() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_settings_stores") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies only monitoring-related RuneStore files to a timestamped recovery
 * directory before the frontend destroys the failed stores.
 */
async backupFailedMonitoringStores() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_failed_monitoring_stores") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a loadout export (JSON) to a user-chosen path.
 *
 * The frontend picks `destination_path` via the dialog plugin's `save()`
 * picker; a `.json` extension is appended when the user omitted it.
 */
async exportLoadout(destinationPath: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_loadout", { destinationPath, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the buff-icon directory as a webview-ready prefix (forward
 * slashes, trailing `/`) for `convertFileSrc` concatenation.
 */
async buffIconDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("buff_icon_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies `source_path` into the buff-icon directory under a
 * content-addressed name, removing superseded icons for the same buff.
 * Returns the stored file name for persistence in settings.
 */
async importBuffIcon(baseId: number, sourcePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_buff_icon", { baseId, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a previously imported icon. Missing files are treated as
 * already deleted.
 */
async deleteBuffIcon(fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_buff_icon", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNetworkDevices() : Promise<Result<Device[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_network_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkNpcapStatus() : Promise<boolean> {
    return await TAURI_INVOKE("check_npcap_status");
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a debug ZIP containing the most recent application log file and returns the path.
 *
 * If `destination_path` is provided, the ZIP is written there. Otherwise it is created
 * in the app log directory.
 */
async createDiagnosticsBundle(destinationPath: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_diagnostics_bundle", { destinationPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diagnostic bridge that lets the frontend write into the same rotating
 * log file. Uses the `app::live` target so release builds keep these
 * records (the release filter keeps `app::live` at info+).
 */
async frontendLog(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("frontend_log", { level, message });
},
async checkGpuSupport() : Promise<GpuSupport> {
    return await TAURI_INVOKE("check_gpu_support");
},
async getLatestModules() : Promise<Result<ModuleInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_modules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeLatestModules(targetAttributes: number[], excludeAttributes: number[], minTotalValue: number | null, minAttrRequirements: Partial<{ [key in number]: number }> | null, useGpu: boolean | null, combinationSize: number | null) : Promise<Result<ModuleSolution[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_latest_modules", { targetAttributes, excludeAttributes, minTotalValue, minAttrRequirements, useGpu, combinationSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceGetStatus(forceRefresh: boolean) : Promise<Result<VoiceStatus, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_get_status", { forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceInstallModel(source: ModelDownloadSource) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_install_model", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCancelModelDownload() : Promise<void> {
    await TAURI_INVOKE("voice_cancel_model_download");
},
async voiceManualImportModel(modelVersion: string, sourceFiles: string[]) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_manual_import_model", { modelVersion, sourceFiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRemoveModel(modelVersion: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_remove_model", { modelVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceVerifyModel() : Promise<Result<ModelState, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_verify_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceInspectFinetunedPackage(packagePath: string) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_inspect_finetuned_package", { packagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceSetFinetunedVoice(packagePath: string, expectedSha256: string, replaceExisting: boolean) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_set_finetuned_voice", { packagePath, expectedSha256, replaceExisting }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRelinkFinetunedVoice(packagePath: string, expectedSha256: string) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_relink_finetuned_voice", { packagePath, expectedSha256 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRemoveFinetunedVoice() : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_remove_finetuned_voice") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceDeleteProfile(profileId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_delete_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCreatePhrase(name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_create_phrase", { name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceUpdatePhrase(id: string, name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_update_phrase", { id, name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceDeletePhrase(id: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_delete_phrase", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceGenerate(request: VoiceGenerateRequestDto) : Promise<Result<GenerationSummary, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_generate", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCancelGeneration() : Promise<void> {
    await TAURI_INVOKE("voice_cancel_generation");
},
async voicePreviewAsset(phraseId: string, assetId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_preview_asset", { phraseId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceTestTrigger(phraseId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_test_trigger", { phraseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Production playback entry point for frontend-detected cues (e.g. a
 * minimap mechanic edge), gated by the same enabled/volume/queue-policy
 * settings as backend rule-triggered cues. Unlike `voice_test_trigger`,
 * never errors on a missing/ungenerated asset: it falls back to a short
 * built-in tone instead.
 */
async voiceEnqueuePhrase(phraseId: string, priority: number) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_enqueue_phrase", { phraseId, priority }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates-or-updates a phrase by `name`, used by the frontend voice
 * binding compiler so "auto"/"custom" bindings resolve to a stable phrase
 * id without the user visiting the phrase library manually.
 */
async voiceUpsertPhrase(name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_upsert_phrase", { name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceStopPlayback() : Promise<void> {
    await TAURI_INVOKE("voice_stop_playback");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AltFreezeConfig = { conditionBuffId: number; freezeDurationMs: number }
export type AppLocale = "zh-CN" | "en-US" | "ja-JP"
export type AttrModifier = { attrId: number; basisPointsPerUnit?: number; maxReductionBasisPoints: number }
export type BossDbmEvent = { skillEffectId: number; baseSkillId: number; durationMs: number; createTimeMs: number; insertion: number; serverTimestampMs: number | null }
/**
 * Represents the health of a boss.
 */
export type BossHealth = {
/**
 * The unique entity UUID of the boss, serialized as a string for JS safety.
 */
entityUuid: string;
/**
 * Monster template ID used by the frontend to resolve the display name.
 */
monsterId: number | null;
/**
 * The current HP of the boss.
 */
currentHp: number | null;
/**
 * The maximum HP of the boss.
 */
maxHp: number | null;
/**
 * Whether the boss is in ActorStateDead.
 */
isDead: boolean }
export type BossMonsterIdsResult = { ids: number[] }
export type BossSummaryDto = { monsterId: number; maxHp: number | null; isDefeated: boolean }
/**
 * Live coverage of one watched buff on the local player. `covered_ms` and
 * `active_ms` follow the shared active-window rule; the frontend only
 * divides and formats.
 */
export type BuffCoverageEntry = { baseId: number; coveredMs: number; activeMs: number; activeNow: boolean; layer: number; count: number }
/**
 * Represents a buff update state.
 */
export type BuffUpdateState = { baseId: number; layer: number; durationMs: number; createTimeMs: number; sourceRemodelLevel: number | null }
export type CounterAction = "reset" | "freeze" | "resetAndFreeze" | "resetAndFreezeKeepCounting" | "resetAndStartCount" | "startCount" | "noOp"
export type CounterRule = { ruleId: number; sources: CounterSource[]; effectSlots: EffectSlotConfig[] }
export type CounterSource = { damageBySkillKey: { skillKeys: number[]; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { damageBySkillKeyOnce: { skillKeys: number[]; increment: number; requiredTypeFlags?: number | null } } | { damageBySkillKeySelfTarget: { skillKeys: number[]; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { anyDamage: { increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { damageTaken: { skillKeys?: number[] | null; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { fightResourceSpent: { resourceId: number; unitsRequired: number; increment: number } } | { buffAdded: { buffId: number; sourceConfigId?: number | null; increment: number } } | { buffLayerSpent: { buffId: number; unitsRequired: number; increment: number } } | { buffDurationTick: { buffId: number; tickIntervalMs: number; increment: number; attrCondition?: TickAttrCondition | null } } | { skillCast: { skillBaseIds: number[]; increment: number } } | { skillDurationTick: { skillBaseId: number; tickIntervalMs: number; increment: number } } | { skillCastComplete: { skillBaseIds: number[]; increment: number } } | { movementDistance: { buffId: number; attrId: number; metersRequired: number; increment: number } }
export type CounterUpdateState = { ruleId: number; slots: SlotUpdateState[] }
/**
 * A single damage event recorded in the 2s sliding window used for death replay.
 */
export type DamageSnapshot = {
/**
 * Absolute timestamp in milliseconds since UNIX epoch.
 */
timestampMs: string;
/**
 * Attacker entity UUID, serialized as a string for JS safety. None for unknown sources.
 */
attackerEntityUuid: string | null;
/**
 * Monster type id of the attacker, if the attacker is a monster. None otherwise.
 */
attackerMonsterTypeId: number | null;
/**
 * Skill key produced by `damage_id::compute_damage_id`.
 */
skillKey: number;
/**
 * Raw damage value.
 */
value: string;
/**
 * Element/property id from the hit packet. None when the packet omitted it.
 */
property?: number | null;
/**
 * Physical/magical mode from the hit packet. None when the packet omitted it.
 */
damageMode?: number | null }
/**
 * A single active buff copied at the moment a death replay record is created.
 */
export type DeathBuffSnapshot = { baseId: number; buffUuid: number; layer: number; durationMs: number; createTimeMs: number; sourceEntityUuid: string | null; sourceConfigId: number | null }
/**
 * Active buffs for one attacker that contributed to a death replay window.
 */
export type DeathParticipantBuffSnapshot = {
/**
 * Attacker entity UUID, serialized as a string for JS safety. None for unknown sources.
 */
entityUuid: string | null;
/**
 * Monster type id of the attacker, if the attacker is a monster. None otherwise.
 */
monsterTypeId: number | null; buffs?: DeathBuffSnapshot[] }
/**
 * A death replay record, capturing the damage taken within the window leading up to a death.
 */
export type DeathRecord = { victimEntityUuid: string; deathTimestampMs: string;
/**
 * Damage snapshots in chronological order (oldest first).
 */
recentDamages?: DamageSnapshot[]; victimBuffs?: DeathBuffSnapshot[]; participantBuffs?: DeathParticipantBuffSnapshot[] }
export type Device = { name: string; description: string | null }
export type EffectSlotConfig = { slotId: number; threshold: number | null; resetBuffId: number; resetSourceConfigId?: number | null; resetBuffTarget?: ResetBuffTarget; onBuffAdd?: CounterAction; onBuffChange?: CounterAction; onBuffRemove?: CounterAction; freezeDurationMs?: number | null; onFreezeExpire?: CounterAction; altFreeze?: AltFreezeConfig | null; thresholdModifier?: AttrModifier | null; freezeDurationModifier?: AttrModifier | null; resetSkillKeys?: number[] | null; onResetSkill?: CounterAction; wrapAtThreshold?: boolean; resetPassiveSkillIds?: number[] | null; onPassiveSkill?: CounterAction; dungeonStartFreezeMs?: number | null }
export type EncounterBuffGraceData = { offsetMs: number; creditedMs: number }
export type EncounterBuffLaneData = { entityId: string; baseId: number;
/**
 * Buff-on time intersected with the active-combat windows (the
 * "true dps" denominator rule). Compare against `active_window_ms`.
 */
coveredActiveMs: number; spans: EncounterBuffSpanData[];
/**
 * Grace credits sampled while this buff was present. Sequence ordering
 * is resolved by the backend before exposing these compact points.
 */
gracePoints?: EncounterBuffGraceData[] }
/**
 * One contiguous wall-clock presence interval of a buff on an entity,
 * as segment offsets clamped to the queried range.
 */
export type EncounterBuffSpanData = { startMs: number; endMsExclusive: number }
export type EncounterBuffTimelineData = { activeWindowMs: number;
/**
 * Non-grace active intervals on the encounter offset axis.
 */
activeSpans?: EncounterBuffSpanData[];
/**
 * First-hit / post-inactivity credits for the denominator.
 */
gracePoints?: EncounterBuffGraceData[]; lanes: EncounterBuffLaneData[] }
/**
 * Per-entity damage hit stream: columnar (offset_ms, amount) pairs ordered
 * by time. Recomputed from raw chunks at query time; never persisted.
 */
export type EncounterDamageHitsData = { entityId: string; offsetsMs: number[];
/**
 * Single-hit amounts saturate at u64::MAX (u128 headroom only matters
 * for accumulated totals, not individual hits).
 */
amounts: number[] }
export type EncounterDeathData = { offsetMs: number; sourceEntityId: string | null; skillId: string | null; replay: DeathRecord | null }
export type EncounterDetailData = { encounterId: number; summary: EncounterSummaryDto; detailAvailable: boolean; qualityFlags: HistoryQualityFlag[]; startMs: number; endMsExclusive: number; totals: EncounterTotalsData; entities: EncounterEntityData[];
/**
 * Always recomputed from chunks on load; stored snapshots leave it empty.
 */
damageHits?: EncounterDamageHitsData[]; markers: EncounterMarkerData[];
/**
 * Always recomputed from chunks on load; `None` for encounters recorded
 * before buff timeline persistence existed.
 */
buffTimeline?: EncounterBuffTimelineData | null }
export type EncounterEntityData = { entityId: string; displayUid: number; name: string | null; classId: number | null; classSpec: number | null;
/**
 * Resolved spec display name; `None` for monsters / unknown specs.
 * `Option` fields decode as `None` from projections stored before this
 * field existed, and are backfilled from `class_spec` at query time.
 */
classSpecName?: string | null; abilityScore: number | null; seasonStrength: number | null; monsterId: number | null; totals: EncounterTotalsData; skills: EncounterSkillData[]; damageTargets: EncounterTargetBreakdownData[]; healingTargets: EncounterTargetBreakdownData[]; takenSources: EncounterSourceBreakdownData[]; deaths: EncounterDeathData[] }
export type EncounterFiltersDto = { bossMonsterIds: number[] | null; sceneIds: number[] | null; playerName: string | null; playerNames: string[] | null; dateFromMs: number | null; dateToMs: number | null; isFavorite: boolean | null }
export type EncounterMarkerData = { offsetMs: number; sequence: number; casterEntityId: string; skillId: string; kind: HistoryCastKind;
/**
 * Fantasy remodel tier when recorded. Absent on older encounters and non-fantasy casts.
 */
remodelLevel?: number | null }
export type EncounterRangeData = { encounterId: number; qualityFlags: HistoryQualityFlag[]; startMs: number; endMsExclusive: number; totals: EncounterTotalsData; entities: EncounterEntityData[];
/**
 * Populated only on the detail path (which shares the range reducer
 * drain); range recounts leave it empty since they render no curves.
 */
damageHits?: EncounterDamageHitsData[]; markers: EncounterMarkerData[] }
export type EncounterSkillData = { skillId: string; metric: HistoryMetric; property: number | null; damageMode: number | null; stats: EncounterStatsData }
export type EncounterSourceBreakdownData = { sourceMonsterId: number | null; stats: EncounterStatsData; skills: EncounterSkillData[] }
export type EncounterStatsData = { total: string; effectiveTotal: string; hits: string; criticalHits: string; criticalTotal: string; luckyHits: string; luckyTotal: string; triggerHits: string; blockedHits: string; luckyBlockHits: string }
export type EncounterSummaryDto = { id: number; startedAtMs: number; endedAtMs: number | null; totalDmg: string; totalHeal: string; sceneId: number | null; dungeonDifficulty: number | null; duration: number; activeCombatDuration: number | null; localPlayerId: number | null; bosses: BossSummaryDto[]; players: PlayerSummaryDto[]; remoteEncounterId: number | null; isFavorite: boolean; detailAvailable: boolean; displayIndex: number }
export type EncounterTargetBreakdownData = { targetEntityId: string; targetDisplayUid: number; targetName: string | null; targetMonsterId: number | null; isBoss: boolean; stats: EncounterStatsData; skills: EncounterSkillData[] }
export type EncounterTotalsData = { damage: string; bossDamage: string; healing: string; effectiveHealing: string; damageTaken: string }
export type EngineBackend = "cpu" | "vulkan"
export type EngineDevice = { backend: EngineBackend; name: string; type: EngineDeviceType }
export type EngineDeviceType = "cpu" | "discreteGpu" | "integratedGpu" | "accelerator" | "unknown"
export type EngineProbe = { engine: string; protocolVersion: number; sourceCommit: string; buildType: string; variant: string; stub: boolean; compiledBackends: EngineBackend[]; devices: EngineDevice[]; supportedLanguages: VoiceLanguage[] }
export type EngineState = { kind: "missing" } | { kind: "ready"; probe: EngineProbe } | { kind: "incompatible"; reason: string } | { kind: "error"; message: string }
export type FactorCounterTemplate = { itemIds?: number[]; sources?: CounterSource[]; effectSlots?: EffectSlotConfig[] }
export type FightResourceEntry = { id: number; value: number }
export type FightResourceState = {
/**
 * The full list of fight resource id/value pairs
 */
entries: FightResourceEntry[];
/**
 * Local timestamp when this state was received
 */
receivedAt: number }
export type FineTunedVoiceMeta = { packagePath: string; transformerPath: string; displayName: string; speakerName: string; speakerTokenId: number; modelSha256: string; sizeBytes: number; quantization: string; tokenizerAbi: string; importedAtMs: number }
export type FineTunedVoiceState = { kind: "notConfigured" } | { kind: "ready"; voice: FineTunedVoiceMeta } | { kind: "missing"; voice: FineTunedVoiceMeta } | { kind: "modified"; voice: FineTunedVoiceMeta }
export type GenerationState = { kind: "idle" } | { kind: "running" } | { kind: "cancelling" }
export type GenerationSummary = { completed: number; failed: number; profileId: string | null; assetIds: string[] }
export type GpuSupport = { cuda_available: boolean; opencl_available: boolean }
export type HateEntry = { entityUuid: string; hateVal: number }
export type HistoryCastKind = "boss_skill" | "fantasy" | "key_skill"
export type HistoryMetric = "damage" | "healing" | "damage_taken"
export type HistoryQualityFlag = "incompleteSegment" | "missingEntityContext" | "saturatedAmount"
/**
 * Health snapshot for the current monster target.
 */
export type HpEntry = { bossEntityUuid: string; monsterId: number; current: number; max: number }
export type HudFrame = { active: boolean; epoch: number; status: LiveStatusPayload | null; buffs: LiveBuffsPayload | null; monster: LiveMonsterPayload | null; fantasy: LiveFantasyPayload | null; snapshot: MinimapSnapshotUpdate | null; skillCasts: MinimapSkillCast[]; skillCastCursor: number; castsReset: boolean }
export type HudFrameRequest = { epoch: number | null; statusRevision: number | null; buffsRevision: number | null; monsterRevision: number | null; fantasyRevision: number | null; snapshotRevision: number | null; skillCastCursor: number | null; gameInterest: boolean; monsterInterest: boolean; minimapInterest: boolean }
export type HudLayoutMigration = { translateMinimap: boolean; minimapOffsetX: number; minimapOffsetY: number }
export type I18nRuntimeSnapshot = { locale: AppLocale }
/**
 * Local player buff list (`live-buffs`), 50ms throttle.
 */
export type LiveBuffsPayload = { revision: number; localBuffs: BuffUpdateState[];
/**
 * Coverage rows for the configured watch list, in configured order.
 */
coverage?: BuffCoverageEntry[] }
/**
 * Combat / segment topic for the live meter window (`live-combat`).
 * `scene_id`/`dungeon_difficulty` live only on the nested `combat` payload;
 * they were duplicated at this level, but every consumer already reads them
 * from `combat.sceneId`/`combat.dungeonDifficulty`.
 */
export type LiveCombatPayload = { revision: number; activeSegmentId: number | null; displayedSegmentId: number | null; combat: LiveDataPayload | null; displayClock: LiveDisplayClock | null; training: TrainingDummyState }
/**
 * Represents a raw
 */
export type LiveDataPayload = { elapsedMs: string; damageElapsedMs: string; activeCombatTimeMs: string; fightStartTimestampMs: string; totalDmg: string; totalDmgBossOnly: string; totalHeal: string; totalEffectiveHeal: string; localPlayerUuid: string; sceneId: number | null; dungeonDifficulty: number | null; isPaused: boolean; bosses: BossHealth[]; entities: RawEntityData[] }
/**
 * Player death replays (`live-deaths`), 50ms throttle. Dirty only when a
 * record is appended or the segment resets, so it never rides the combat
 * publication cadence.
 */
export type LiveDeathsPayload = { revision: number; deaths: DeathRecord[] }
/**
 * Wall-clock anchors for the live header timer. Interpolation happens in
 * the UI; this DTO is never the DPS / history duration clock.
 */
export type LiveDisplayClock = { startedAtWallMs: number; accumulatedPausedMs: number; pausedAtWallMs: number | null; endedAtWallMs: number | null }
/**
 * Fantasy cast icons shared by live + monster overlay (`live-fantasy`).
 */
export type LiveFantasyPayload = { revision: number; teammateFantasies: TeammateFantasyState[] }
/**
 * Monster overlay topic (`live-monster`), 50ms throttle.
 */
export type LiveMonsterPayload = { revision: number; bossBuffs: Partial<{ [key in string]: BuffUpdateState[] }>; teammateBuffs: Partial<{ [key in string]: BuffUpdateState[] }>; bossMechanics: BossDbmEvent[]; hateLists: Partial<{ [key in string]: HateEntry[] }>; stun: StunEntry[]; hp: HpEntry[]; playerNames: Partial<{ [key in string]: string }>; monsterIds: Partial<{ [key in string]: number }> }
export type LivePullWindow = "live" | "hud-overlay"
export type LiveRuntimeSnapshot = { eventUpdateRateMs: number; trainingWindowMs: number; trainingLockPolicy: TrainingLockPolicy }
/**
 * Scene topic payload (`live-scene`). Besides the scene id this low-frequency
 * channel also carries the local player's profession / talent branch, which
 * `main` uses to drive spec-linked loadout auto-switching.
 */
export type LiveScenePayload = { revision: number; sceneId: number | null; dungeonDifficulty: number | null;
/**
 * Local player's current profession id (`cur_profession_id`).
 */
localClassId: number | null;
/**
 * Local player's active talent branch (`TalentStageTable` cfg id).
 */
localTalentStageCfgId: number | null }
/**
 * Skill CD / panel attrs / fight resource / shields / counters
 * (`live-status`). Published on the same 50ms cadence as the other overlay
 * pull topics when dirty. Overlay windows still read this through invoke
 * pull; it is not emitted as a WebView event.
 */
export type LiveStatusPayload = { revision: number; counters: CounterUpdateState[]; factorCounters: CounterUpdateState[]; factorSourceItemIds: number[]; factorSlotItemIds: number[];
/**
 * Highest deep-sleep (800522) `seasonId` resolved from the last
 * container sync/patch; `0` before any season data has been observed.
 */
seasonId: number; seasonActiveTemplateIds: number[]; skillCds: SkillCdState[]; panelAttrs: PanelAttrState[]; shieldCurrentHp: number; shieldMaxHp: number; shieldEntries: ShieldDetailEntry[]; fightResource: FightResourceState | null }
export type LiveWindowFrame = { active: boolean; epoch: number; combat: LiveCombatPayload | null; fantasy: LiveFantasyPayload | null; deaths: LiveDeathsPayload | null }
export type LiveWindowFrameRequest = { epoch: number | null; combatRevision: number | null; fantasyRevision: number | null; deathsRevision: number | null; includeDeaths: boolean }
/**
 * A single active buff fact currently known to the minimap.
 */
export type MinimapBuffFact = {
/**
 * Entity UUID carrying this buff.
 */
targetEntityUuid: string;
/**
 * Runtime buff instance id.
 */
buffUuid: number;
/**
 * Buff template id.
 */
baseId: number;
/**
 * Current stack/layer.
 */
layer: number;
/**
 * Buff creation time in the local time domain (server_clock_offset applied).
 */
createTimeMs: number;
/**
 * Buff duration in milliseconds (0 if unknown/permanent).
 */
durationMs: number;
/**
 * Runtime source/caster entity when the server includes it.
 */
fireUuid: string | null;
/**
 * Skill/buff config id that caused this buff, when available.
 */
sourceConfigId: number | null;
/**
 * `PlayEffect` effect ids from the buff's logic_effects, in wire order.
 */
effectIds: number[] }
/**
 * A single entity fact rendered/interpreted by the 2D minimap overlay.
 */
export type MinimapEntity = {
/**
 * Entity UUID as string (avoids JS bigint truncation, matching existing convention).
 */
entityUuid: string;
/**
 * Raw entity type normalized for frontend use.
 */
entityType: MinimapEntityType;
/**
 * What the entity is, used by the frontend to pick color/size.
 */
kind: MinimapEntityKind;
/**
 * Horizontal map coordinate.
 */
x: number;
/**
 * Vertical game coordinate.
 */
y: number;
/**
 * Depth map coordinate (game `z`, not vertical height).
 */
z: number;
/**
 * Display name when known.
 */
name: string | null;
/**
 * Monster template id when the entity is a monster.
 */
monsterId: number | null;
/**
 * Yaw facing in degrees when known (attr 0x32, stored as centidegrees).
 */
facing: number | null;
/**
 * Whether the entity is currently in the dead actor state.
 */
isDead: boolean;
/**
 * Top-level summoner/owner UUID when present.
 */
topSummonerId: string | null }
/**
 * Classification of an entity rendered on the minimap.
 */
export type MinimapEntityKind =
/**
 * The local player.
 */
"local" |
/**
 * A teammate (party member that is not the local player).
 */
"teammate" |
/**
 * A boss-tier monster.
 */
"boss" |
/**
 * Any other monster.
 */
"monster" |
/**
 * A non-monster dummy/mechanic helper entity.
 */
"dummy" |
/**
 * Other renderable non-character entities.
 */
"other"
/**
 * Raw entity type exposed to the minimap as a reusable fact.
 */
export type MinimapEntityType = "unknown" | "monster" | "npc" | "sceneObject" | "zone" | "bullet" | "clientBullet" | "pet" | "char" | "dummy" | "drop" | "field" | "trap" | "collection" | "staticObject" | "vehicle" | "toy" | "communityHouse" | "houseItem" | "other"
/**
 * One in-game player marker to render on the minimap.
 */
export type MinimapMarker = {
/**
 * Displayed marker number 1..=6, derived as `skill_id - MARKER_SKILL_ID_BASE`.
 */
marker: number; skillId: number; x: number | null; z: number | null }
/**
 * One monster skill cast event observed from `ATTR_SKILL_ID` (attribute 100).
 */
export type MinimapSkillCast = {
/**
 * Entity UUID that emitted the skill cast.
 */
entityUuid: string;
/**
 * Skill template id.
 */
skillId: number;
/**
 * Local receive time in milliseconds.
 */
timeMs: number;
/**
 * World X position of the caster at cast time, when known.
 */
x: number | null;
/**
 * World Z position of the caster at cast time, when known.
 */
z: number | null;
/**
 * Yaw facing in degrees at cast time, when known.
 */
facing: number | null }
/**
 * One frame of minimap data for a single scene.
 */
export type MinimapSnapshot = {
/**
 * Current scene id.
 */
sceneId: number;
/**
 * Local player UUID for frontend grouping and display.
 */
localPlayerUuid: string;
/**
 * All tracked entities that currently have a known position.
 */
entities: MinimapEntity[];
/**
 * Active buff facts selected by the scene/mechanic extraction config.
 */
buffs: MinimapBuffFact[];
/**
 * Active in-game player markers
 */
markers: MinimapMarker[] }
export type MinimapSnapshotUpdate = { revision: number; snapshot: MinimapSnapshot | null }
export type ModelDownloadSource = "auto" | "huggingFace" | "hfMirror"
export type ModelState = { kind: "notInstalled" } | { kind: "installing" } | { kind: "ready"; version: string } | { kind: "corrupt"; version: string; reason: string }
export type ModuleInfo = { name: string; config_id: number; uuid: number; quality: number; parts: ModulePart[] }
export type ModulePart = { id: number; name: string; value: number }
export type ModuleSolution = { modules: ModuleInfo[]; score: number; attr_breakdown: Partial<{ [key in string]: number }> }
export type MonitorRuntimeSnapshot = { i18n: I18nRuntimeSnapshot; live: LiveRuntimeSnapshot; skill: SkillRuntimeSnapshot; monster: MonsterRuntimeSnapshot; teammate: TeammateRuntimeSnapshot; voice: VoiceRuntimeSnapshot }
/**
 * Which caster population a monster-buff voice rule observes.
 */
export type MonsterBuffSourceScope = "anySource" | "localPlayerSource"
export type MonsterRuntimeSnapshot = { enabled: boolean; globalIds: number[]; selfAppliedIds: number[]; monitorAllSelfApplied: boolean }
export type PanelAttrState = { attrId: number; value: number }
/**
 * Damage taken by a defender, aggregated by the attacking monster's template.
 */
export type PerSourceStats = {
/**
 * Monster template id of the attacker. None when the source was unknown.
 */
sourceMonsterId: number | null; totalValue: string; taken: RawCombatStats; skills: Partial<{ [key in number]: RawSkillStats }> }
export type PlayerNamesResult = { names: string[] }
export type PlayerSummaryDto = { name: string; classId: number }
export type RawCombatStats = { total: string; effectiveTotal: string; hits: string; critHits: string; critTotal: string; luckyHits: string; luckyTotal: string; triggerHits: string; blockHits: string; luckyBlockHits: string }
export type RawEntityData = { entityUuid: string; displayUid: number; name: string; classId: number; classSpec: number; className: string; classSpecName: string; abilityScore: number; seasonStrength: number; damage: RawCombatStats; damageBossOnly: RawCombatStats; healing: RawCombatStats; taken: RawCombatStats; dmgSkills: Partial<{ [key in number]: RawSkillStats }>; healSkills: Partial<{ [key in number]: RawSkillStats }>; takenSkills: Partial<{ [key in number]: RawSkillStats }>; takenPerSource: PerSourceStats[] }
export type RawSkillStats = { totalValue: string; effectiveTotalValue: string; hits: string; critHits: string; critTotalValue: string; luckyHits: string; luckyTotalValue: string; property: number | null; damageMode: number | null; triggerHits: string; blockHits: string; luckyBlockHits: string }
export type RecentEncountersResult = { rows: EncounterSummaryDto[]; totalCount: number }
export type ResetBuffTarget = "selfPlayer" | "anyTeam"
export type SceneIdsResult = { ids: number[] }
/**
 * A single shield entry parsed from attr 60050.
 */
export type ShieldDetailEntry = { buffUuid: number; displayType: number;
/**
 * Current shield value (field 3)
 */
current: number;
/**
 * Initial shield value when the buff was applied (field 4)
 */
initialShield: number;
/**
 * Max shield value (field 5)
 */
maxShield: number;
/**
 * Base ID of the buff (from buff monitor lookup), 0 if unknown
 */
baseId: number;
/**
 * Local-clock expiry timestamp in ms, 0 if unknown or permanent
 */
expireTimeMs: number }
/**
 * Represents a skill cooldown state.
 */
export type SkillCdState = {
/**
 * The skill level ID.
 */
skillLevelId: number;
/**
 * The cooldown begin timestamp
 */
beginTime: number;
/**
 * The total duration of the cooldown in milliseconds.
 * -1 indicates a charge/resource style entry.
 */
duration: number;
/**
 * The cooldown type enum value
 */
skillCdType: number;
/**
 * The server-reported valid cooldown time in milliseconds.
 */
validCdTime: number;
/**
 * Local timestamp when this cooldown state was received
 */
receivedAt: number;
/**
 * Cooldown duration after applying AttrSkillCD/AttrSkillCDPCT and TempAttr rules.
 */
calculatedDuration: number;
/**
 * Cooldown accelerate rate for this skill
 */
cdAccelerateRate: number }
export type SkillRuntimeSnapshot = { enabled: boolean; monitoredSkillIds: number[]; monitoredBuffIds: number[]; monitorAllBuff: boolean; monitoredPanelAttrIds: number[]; buffCounterRules: CounterRule[]; seasonCultivateFactorTemplates: FactorCounterTemplate[];
/**
 * Coverage watch list: these buff ids are tracked for live coverage on
 * the local player and persisted as timeline edges for all players.
 */
buffTimelineIds: number[] }
export type SlotUpdateState = { slotId: number; currentCount: number; threshold: number | null; effectiveThreshold: number | null; isCounting: boolean; resetBuffActive: boolean; freezeUntilMs: number | null; freezeDurationMs: number | null; effectiveFreezeDurationMs: number | null }
/**
 * Stamina/resilience snapshot for a single monster target.
 * `current` depletes from `max` as the monster is staggered; reaching 0
 * means the stagger threshold has been hit.
 */
export type StunEntry = { bossEntityUuid: string; monsterId: number; current: number; max: number }
export type TeammateFantasyState = { summonUuid: string; summonerUuid: string; summonerName: string | null; monsterId: number;
/**
 * Normalized resonance skill id that summoned this fantasy, when known.
 */
resonanceSkillId: number | null; remodelLevel: number; detectedAtMs: number }
export type TeammateRuntimeSnapshot = { enabled: boolean; anySourceIds: number[]; localPlayerSourceIds: number[]; targetSelfSourceIds: number[]; monitorAll: boolean }
export type TickAttrCondition = { attrId: number; requiredValue: number }
export type TrainingDummyPhase = "idle" | "armed" | "running" | "finished"
export type TrainingDummyState = { phase: TrainingDummyPhase }
export type TrainingLockPolicy = "eliteDummies" | "firstMonster"
/**
 * A single generated take (WAV) for a phrase, using a specific profile/model/params.
 */
export type VoiceAssetMeta = { id: string; phraseId: string; source: VoiceAssetSource; modelVersion: string;
/**
 * Fingerprint of (text, language, profile version, model sha, generation params).
 * Used to detect staleness without storing absolute paths in rules.
 */
paramsFingerprint: string; createdAtMs: number; durationSec: number; sampleRate: number;
/**
 * True when the phrase/profile/model changed after this asset was generated.
 */
stale: boolean }
export type VoiceAssetSource = { kind: "cloneProfile"; profileId: string } | { kind: "fineTuned"; modelSha256: string; speakerName: string; speakerTokenId: number } |
/**
 * A final, ready-to-play WAV shipped with the application.
 */
{ kind: "bundledPrompt"; key: string; locale: VoicePresetLocale; revision: number }
export type VoiceBackendInventory = { cpu: VoiceBackendStatus; vulkan: VoiceBackendStatus; recommended: EngineBackend }
export type VoiceBackendStatus = { backend: EngineBackend; engine: EngineState; componentVersion: string | null; updateAvailable: boolean }
/**
 * The full persisted voice catalog (`catalog.json`).
 */
export type VoiceCatalog = { schemaVersion: number; profiles: VoiceProfileMeta[]; phrases: VoicePhraseMeta[]; assets: VoiceAssetMeta[]; installedModelVersion: string | null; installedModelSha256: string | null; fineTunedVoice: FineTunedVoiceMeta | null }
export type VoiceCommandError = { code: string; message: string; retriable: boolean }
export type VoiceGenerateRequestDto = { source: VoiceSourceSelectionDto; phraseIds: string[]; backendPreference?: VoiceGenerationBackend }
export type VoiceGenerationBackend = "auto" | "cpu" | "vulkan"
export type VoiceLanguage = "zhCn" | "enUs" | "jaJp"
export type VoiceOperationState = { kind: "idle" } | { kind: "installingModel"; cancelling: boolean } | { kind: "importingModel" } | { kind: "verifyingModel" } | { kind: "removingModel" } | { kind: "generating"; cancelling: boolean } | { kind: "updatingCatalog" }
/**
 * A fixed phrase (short line) that can be synthesized ahead of time, e.g.
 * "机制来了" / "增益结束".
 */
export type VoicePhraseMeta = { id: string; name: string; text: string; language: VoiceLanguage; activeAssetId: string | null; updatedAtMs: number }
/**
 * A UI locale with a bundled reference voice. Deliberately distinct from
 * [`super::models::VoiceLanguage`], which tags the *text* of a phrase and
 * drives the sidecar's codec language id: a Chinese-locale user can still
 * author (and hear synthesized) an English or Japanese phrase, and should
 * keep hearing it in the Chinese preset voice unless they pick a different
 * source explicitly.
 */
export type VoicePresetLocale = "zh-CN" | "en-US" | "ja-JP"
/**
 * Identifies which bundled reference file (and manifest revision) a cloned
 * profile was extracted from. Stored on [`super::models::VoiceProfileMeta`]
 * so a later generation can detect that the bundled audio moved on to a
 * new revision and re-extract rather than reuse a stale embedding.
 */
export type VoicePresetTag = { locale: VoicePresetLocale; revision: number }
/**
 * A persisted speaker profile (voice clone), backed by a `.q3sp` file on disk.
 */
export type VoiceProfileMeta = { id: string; name: string; createdAtMs: number; modelVersion: string; embeddingDim: number; modelSha256: string; refAudioSha256: string;
/**
 * Whether the original reference WAV was kept on disk (opt-in).
 */
refAudioRetained: boolean;
/**
 * Set when this profile was auto-created from a bundled preset
 * reference (see `voice::presets`) rather than audio the user
 * supplied, so generation can detect a stale preset (bundled asset
 * revision bumped) and re-extract instead of silently reusing
 * outdated audio. `None` for user-provided clone profiles.
 */
preset: VoicePresetTag | null }
/**
 * Playback queue policy when the queue is full or a higher priority cue arrives.
 */
export type VoiceQueuePolicy =
/**
 * Drop new low-priority cues when the queue is full.
 */
"dropLowPriority" |
/**
 * Higher priority cues interrupt whatever is currently playing.
 */
"interruptForHigherPriority"
/**
 * A user-defined rule mapping a trigger to a phrase to play.
 */
export type VoiceRule = { id: string; enabled: boolean; trigger: VoiceTrigger; phraseId: string;
/**
 * 0 = lowest, 255 = highest. Higher priority can interrupt lower priority playback.
 */
priority: number; cooldownMs: number; phraseIdByTier?: Partial<{ [key in number]: string }> | null }
/**
 * Persisted + hot-synced runtime settings for the voice feature, embedded as
 * a sub-section of `MonitorRuntimeSnapshot` alongside skill/monster/teammate.
 */
export type VoiceRuntimeSnapshot = { enabled: boolean; volume: number; queuePolicy: VoiceQueuePolicy; rules: VoiceRule[] }
export type VoiceSourceSelectionDto = { mode: "cloneNew"; name: string; referenceWavPath: string; keepReference?: boolean } | { mode: "cloneExisting"; profileId: string } |
/**
 * Auto-selects the bundled reference voice for a UI locale, extracting
 * (and thereafter reusing) a clone profile from it on demand.
 */
{ mode: "preset"; locale: VoicePresetLocale } | { mode: "fineTuned" }
/**
 * Overall status snapshot returned to the frontend for the voice feature.
 */
export type VoiceStatus = { catalog: VoiceCatalog; model: ModelState; operation: VoiceOperationState; generation: GenerationState; engine: EngineState; backends: VoiceBackendInventory; fineTunedVoice: FineTunedVoiceState }
/**
 * Which real-time game event should trigger a voice cue.
 */
export type VoiceTrigger =
/**
 * The local player gains a buff with this base id.
 */
{ kind: "buffGained"; buffId: number } |
/**
 * The local player loses (all layers of) a buff with this base id.
 */
{ kind: "buffLost"; buffId: number } |
/**
 * The local player's buff with this base id will expire in
 * `seconds_before` seconds (fires once per buff instance).
 */
{ kind: "buffExpiring"; buffId: number; secondsBefore: number } |
/**
 * The current attack target (monster) gains a buff with this base id.
 */
{ kind: "monsterBuffGained"; buffId: number; sourceScope: MonsterBuffSourceScope } |
/**
 * The current attack target (monster) loses (all layers of) a buff
 * with this base id.
 */
{ kind: "monsterBuffLost"; buffId: number; sourceScope: MonsterBuffSourceScope } |
/**
 * The current attack target's buff with this base id will expire in
 * `seconds_before` seconds (fires once per buff instance).
 */
{ kind: "monsterBuffExpiring"; buffId: number; secondsBefore: number; sourceScope: MonsterBuffSourceScope } |
/**
 * A boss "DBM" mechanic world event fires with this base skill id.
 */
{ kind: "bossDbm"; baseSkillId: number } |
/**
 * A boss "DBM" mechanic's timer will expire in `seconds_before` seconds.
 */
{ kind: "bossDbmExpiring"; baseSkillId: number; secondsBefore: number } |
/**
 * A counter rule's slot count reaches its effective threshold.
 */
{ kind: "counterThreshold"; ruleId: number; slotId: number } |
/**
 * A counter rule's slot freeze window will expire in
 * `seconds_before` seconds.
 */
{ kind: "counterExpiring"; ruleId: number; slotId: number; secondsBefore: number } |
/**
 * The matchmaking queue popped and is waiting for acceptance.
 */
{ kind: "matchmakingPopped" } |
/**
 * The party leader started a ready check.
 */
{ kind: "readyCheckStarted" } |
/**
 * A team activity vote started.
 */
{ kind: "teamVoteStarted" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
