// This file is generated by `npm run bindings`.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Enables blur on the live meter window.
 *
 * # Arguments
 *
 * * `app` - A handle to the Tauri application instance.
 */
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
/**
 * Disables blur on the live meter window.
 *
 * # Arguments
 *
 * * `app` - A handle to the Tauri application instance.
 */
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
/**
 * Resets the encounter.
 *
 * # Arguments
 *
 * * `state_manager` - The state manager.
 *
 * # Returns
 *
 * * `Result<(), String>` - An empty result.
 */
async resetEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles pausing the encounter.
 *
 * # Arguments
 *
 * * `state_manager` - The state manager.
 *
 * # Returns
 *
 * * `Result<(), String>` - An empty result.
 */
async togglePauseEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pause_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTrainingDummy() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_training_dummy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTrainingDummy() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_training_dummy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAndApplyMonitorRuntimeSnapshot(snapshot: MonitorRuntimeSnapshot) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_and_apply_monitor_runtime_snapshot", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of recent encounters.
 *
 * # Arguments
 *
 * * `limit` - The maximum number of encounters to return.
 * * `offset` - The number of encounters to skip.
 *
 * # Returns
 *
 * * `Result<RecentEncountersResult, String>` - A list of recent encounters.
 */
async getRecentEncounters(limit: number, offset: number) : Promise<Result<RecentEncountersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_encounters", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of unique scene IDs.
 *
 * # Returns
 *
 * * `Result<SceneIdsResult, String>` - A list of unique scene IDs.
 */
async getUniqueSceneIds() : Promise<Result<SceneIdsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_scene_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of unique boss monster template IDs.
 *
 * # Returns
 *
 * * `Result<BossMonsterIdsResult, String>` - A list of unique boss monster IDs.
 */
async getUniqueBossMonsterIds() : Promise<Result<BossMonsterIdsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unique_boss_monster_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of player names filtered by a prefix.
 *
 * This will return up to 5 matching player names (to keep the UI responsive).
 *
 * # Arguments
 *
 * * `prefix` - The prefix to filter by.
 *
 * # Returns
 *
 * * `Result<PlayerNamesResult, String>` - A list of player names.
 */
async getPlayerNamesFiltered(prefix: string) : Promise<Result<PlayerNamesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_names_filtered", { prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of recent encounters filtered by the given criteria.
 *
 * # Arguments
 *
 * * `limit` - The maximum number of encounters to return.
 * * `offset` - The number of encounters to skip.
 * * `filters` - The filters to apply.
 *
 * # Returns
 *
 * * `Result<RecentEncountersResult, String>` - A list of recent encounters.
 */
async getRecentEncountersFiltered(limit: number, offset: number, filters: EncounterFiltersDto | null) : Promise<Result<RecentEncountersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_encounters_filtered", { limit, offset, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets an encounter by its ID.
 *
 * # Arguments
 *
 * * `encounter_id` - The ID of the encounter.
 *
 * # Returns
 *
 * * `Result<EncounterSummaryDto, String>` - The encounter summary.
 */
async getEncounterById(encounterId: number) : Promise<Result<EncounterSummaryDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_by_id", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets raw actor entities for a historical encounter.
 */
async getEncounterEntitiesRaw(encounterId: number) : Promise<Result<HistoryEntityData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_entities_raw", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an encounter by its ID.
 *
 * # Arguments
 *
 * * `encounter_id` - The ID of the encounter to delete.
 *
 * # Returns
 *
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async deleteEncounter(encounterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounter", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple encounters by ID.
 *
 * # Arguments
 *
 * * `ids` - The IDs of the encounters to delete.
 *
 * # Returns
 *
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async deleteEncounters(ids: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounters", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the favorite status of an encounter.
 *
 * # Arguments
 *
 * * `id` - The ID of the encounter.
 * * `is_favorite` - The new favorite status.
 *
 * # Returns
 *
 * * `Result<(), String>` - An empty result indicating success or failure.
 */
async toggleFavoriteEncounter(id: number, isFavorite: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_favorite_encounter", { id, isFavorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A Tauri command to get a list of recent players.
 *
 * # Arguments
 *
 * * `limit` - The maximum number of players to return.
 *
 * # Returns
 *
 * * `Result<Vec<(i64, String)>, String>` - A list of recent players.
 */
async getRecentPlayersCommand(limit: number) : Promise<Result<([number, string])[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_players_command", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A Tauri command to get the name of a player by their UID.
 *
 * # Arguments
 *
 * * `uid` - The UID of the player.
 *
 * # Returns
 *
 * * `Result<Option<String>, String>` - The name of the player, or `None` if not found.
 */
async getPlayerNameCommand(uid: number) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_name_command", { uid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePacketCaptureSettings(method: string, npcapDevice: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_packet_capture_settings", { method, npcapDevice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Best-effort backup of the persisted settings stores before running a
 * one-time frontend migration. Copies every RuneStore JSON file into
 * `tauri-plugin-svelte/backup-v1/` without replacing the first snapshot.
 */
async backupSettingsStores() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_settings_stores") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies only monitoring-related RuneStore files to a timestamped recovery
 * directory before the frontend destroys the failed stores.
 */
async backupFailedMonitoringStores() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_failed_monitoring_stores") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a loadout export (JSON) to a user-chosen path.
 *
 * The frontend picks `destination_path` via the dialog plugin's `save()`
 * picker; a `.json` extension is appended when the user omitted it.
 */
async exportLoadout(destinationPath: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_loadout", { destinationPath, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the buff-icon directory as a webview-ready prefix (forward
 * slashes, trailing `/`) for `convertFileSrc` concatenation.
 */
async buffIconDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("buff_icon_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies `source_path` into the buff-icon directory under a
 * content-addressed name, removing superseded icons for the same buff.
 * Returns the stored file name for persistence in settings.
 */
async importBuffIcon(baseId: number, sourcePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_buff_icon", { baseId, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a previously imported icon. Missing files are treated as
 * already deleted.
 */
async deleteBuffIcon(fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_buff_icon", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNetworkDevices() : Promise<Result<Device[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_network_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkNpcapStatus() : Promise<boolean> {
    return await TAURI_INVOKE("check_npcap_status");
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a debug ZIP containing the most recent application log file and returns the path.
 *
 * If `destination_path` is provided, the ZIP is written there. Otherwise it is created
 * in the app log directory.
 */
async createDiagnosticsBundle(destinationPath: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_diagnostics_bundle", { destinationPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkGpuSupport() : Promise<GpuSupport> {
    return await TAURI_INVOKE("check_gpu_support");
},
async getLatestModules() : Promise<Result<ModuleInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_modules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeLatestModules(targetAttributes: number[], excludeAttributes: number[], minTotalValue: number | null, minAttrRequirements: Partial<{ [key in number]: number }> | null, useGpu: boolean | null, combinationSize: number | null) : Promise<Result<ModuleSolution[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_latest_modules", { targetAttributes, excludeAttributes, minTotalValue, minAttrRequirements, useGpu, combinationSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceGetStatus(forceRefresh: boolean) : Promise<Result<VoiceStatus, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_get_status", { forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceInstallModel(source: ModelDownloadSource) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_install_model", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCancelModelDownload() : Promise<void> {
    await TAURI_INVOKE("voice_cancel_model_download");
},
async voiceManualImportModel(modelVersion: string, sourceFiles: string[]) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_manual_import_model", { modelVersion, sourceFiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRemoveModel(modelVersion: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_remove_model", { modelVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceVerifyModel() : Promise<Result<ModelState, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_verify_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceInspectFinetunedPackage(packagePath: string) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_inspect_finetuned_package", { packagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceSetFinetunedVoice(packagePath: string, expectedSha256: string, replaceExisting: boolean) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_set_finetuned_voice", { packagePath, expectedSha256, replaceExisting }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRelinkFinetunedVoice(packagePath: string, expectedSha256: string) : Promise<Result<FineTunedVoiceMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_relink_finetuned_voice", { packagePath, expectedSha256 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceRemoveFinetunedVoice() : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_remove_finetuned_voice") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceDeleteProfile(profileId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_delete_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCreatePhrase(name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_create_phrase", { name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceUpdatePhrase(id: string, name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_update_phrase", { id, name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceDeletePhrase(id: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_delete_phrase", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceGenerate(request: VoiceGenerateRequestDto) : Promise<Result<GenerationSummary, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_generate", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceCancelGeneration() : Promise<void> {
    await TAURI_INVOKE("voice_cancel_generation");
},
async voicePreviewAsset(phraseId: string, assetId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_preview_asset", { phraseId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceTestTrigger(phraseId: string) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_test_trigger", { phraseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Production playback entry point for frontend-detected cues (e.g. a
 * minimap mechanic edge), gated by the same enabled/volume/queue-policy
 * settings as backend rule-triggered cues. Unlike `voice_test_trigger`,
 * never errors on a missing/ungenerated asset: it falls back to a short
 * built-in tone instead.
 */
async voiceEnqueuePhrase(phraseId: string, priority: number) : Promise<Result<null, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_enqueue_phrase", { phraseId, priority }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates-or-updates a phrase by `name`, used by the frontend voice
 * binding compiler so "auto"/"custom" bindings resolve to a stable phrase
 * id without the user visiting the phrase library manually.
 */
async voiceUpsertPhrase(name: string, text: string, language: VoiceLanguage) : Promise<Result<VoicePhraseMeta, VoiceCommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_upsert_phrase", { name, text, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async voiceStopPlayback() : Promise<void> {
    await TAURI_INVOKE("voice_stop_playback");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AltFreezeConfig = { conditionBuffId: number; freezeDurationMs: number }
export type AppLocale = "zh-CN" | "en-US" | "ja-JP"
export type AttrModifier = { attrId: number; basisPointsPerUnit?: number; maxReductionBasisPoints: number }
/**
 * The result of a query for boss monster template IDs.
 */
export type BossMonsterIdsResult = {
/**
 * A list of boss monster template IDs.
 */
ids: number[] }
/**
 * A summary of a boss.
 */
export type BossSummaryDto = {
/**
 * The monster template ID.
 */
monsterId: number;
/**
 * The maximum HP of the monster.
 */
maxHp: number | null;
/**
 * Whether the boss was defeated.
 */
isDefeated: boolean }
export type CounterAction = "reset" | "freeze" | "resetAndFreeze" | "resetAndFreezeKeepCounting" | "resetAndStartCount" | "startCount" | "noOp"
export type CounterRule = { ruleId: number; sources: CounterSource[]; effectSlots: EffectSlotConfig[] }
export type CounterSource = { damageBySkillKey: { skillKeys: number[]; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { damageBySkillKeyOnce: { skillKeys: number[]; increment: number; requiredTypeFlags?: number | null } } | { damageBySkillKeySelfTarget: { skillKeys: number[]; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { anyDamage: { increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { damageTaken: { skillKeys?: number[] | null; increment: number; hitsRequired?: number | null; requiredTypeFlags?: number | null } } | { fightResourceSpent: { resourceId: number; unitsRequired: number; increment: number } } | { buffAdded: { buffId: number; sourceConfigId?: number | null; increment: number } } | { buffLayerSpent: { buffId: number; unitsRequired: number; increment: number } } | { buffDurationTick: { buffId: number; tickIntervalMs: number; increment: number; attrCondition?: TickAttrCondition | null } } | { skillCast: { skillBaseIds: number[]; increment: number } } | { skillDurationTick: { skillBaseId: number; tickIntervalMs: number; increment: number } } | { skillCastComplete: { skillBaseIds: number[]; increment: number } } | { movementDistance: { buffId: number; attrId: number; metersRequired: number; increment: number } }
/**
 * A single damage event recorded in the 2s sliding window used for death replay.
 */
export type DamageSnapshot = {
/**
 * Absolute timestamp in milliseconds since UNIX epoch.
 */
timestampMs: number;
/**
 * Attacker entity UUID, serialized as a string for JS safety. None for unknown sources.
 */
attackerEntityUuid: string | null;
/**
 * Monster type id of the attacker, if the attacker is a monster. None otherwise.
 */
attackerMonsterTypeId: number | null;
/**
 * Skill key produced by `damage_id::compute_damage_id`.
 */
skillKey: number;
/**
 * Raw damage value.
 */
value: number }
/**
 * A single active buff copied at the moment a death replay record is created.
 */
export type DeathBuffSnapshot = { baseId: number; buffUuid: number; layer: number; durationMs: number; createTimeMs: number; sourceEntityUuid: string | null; sourceConfigId: number | null }
/**
 * Active buffs for one attacker that contributed to a death replay window.
 */
export type DeathParticipantBuffSnapshot = {
/**
 * Attacker entity UUID, serialized as a string for JS safety. None for unknown sources.
 */
entityUuid: string | null;
/**
 * Monster type id of the attacker, if the attacker is a monster. None otherwise.
 */
monsterTypeId: number | null; buffs?: DeathBuffSnapshot[] }
/**
 * A death replay record, capturing the damage taken within the window leading up to a death.
 */
export type DeathRecord = { victimEntityUuid: string; deathTimestampMs: number;
/**
 * Damage snapshots in chronological order (oldest first).
 */
recentDamages?: DamageSnapshot[]; victimBuffs?: DeathBuffSnapshot[]; participantBuffs?: DeathParticipantBuffSnapshot[] }
export type Device = { name: string; description: string | null }
export type EffectSlotConfig = { slotId: number; threshold: number | null; resetBuffId: number; resetSourceConfigId?: number | null; resetBuffTarget?: ResetBuffTarget; onBuffAdd?: CounterAction; onBuffChange?: CounterAction; onBuffRemove?: CounterAction; freezeDurationMs?: number | null; onFreezeExpire?: CounterAction; altFreeze?: AltFreezeConfig | null; thresholdModifier?: AttrModifier | null; freezeDurationModifier?: AttrModifier | null; resetSkillKeys?: number[] | null; onResetSkill?: CounterAction; dungeonStartFreezeMs?: number | null }
/**
 * Filters for querying encounters.
 */
export type EncounterFiltersDto = {
/**
 * A list of boss monster template IDs to filter by.
 */
bossMonsterIds: number[] | null;
/**
 * A list of scene IDs to filter by.
 */
sceneIds: number[] | null;
/**
 * A player name to filter by.
 */
playerName: string | null;
/**
 * A list of player names to filter by.
 */
playerNames: string[] | null;
/**
 * The start date to filter by in milliseconds since the Unix epoch.
 */
dateFromMs: number | null;
/**
 * The end date to filter by in milliseconds since the Unix epoch.
 */
dateToMs: number | null;
/**
 * Whether to filter by favorite encounters.
 */
isFavorite: boolean | null }
/**
 * A summary of an encounter.
 */
export type EncounterSummaryDto = {
/**
 * The ID of the encounter.
 */
id: number;
/**
 * The start time of the encounter in milliseconds since the Unix epoch.
 */
startedAtMs: number;
/**
 * The end time of the encounter in milliseconds since the Unix epoch.
 */
endedAtMs: number | null;
/**
 * The total damage dealt in the encounter.
 */
totalDmg: number;
/**
 * The total healing done in the encounter.
 */
totalHeal: number;
/**
 * The ID of the scene where the encounter took place.
 */
sceneId: number | null;
/**
 * Dungeon difficulty suffix for the scene, if known.
 */
dungeonDifficulty: number | null;
/**
 * The duration of the encounter in seconds.
 */
duration: number;
/**
 * The accumulated active combat duration in seconds.
 */
activeCombatDuration: number | null;
/**
 * The UID of the local player for this encounter.
 */
localPlayerId: number | null;
/**
 * A list of bosses in the encounter.
 */
bosses: BossSummaryDto[];
/**
 * A list of players in the encounter.
 */
players: PlayerSummaryDto[];
/**
 * The encounter ID on the remote website/server after successful upload.
 */
remoteEncounterId: number | null;
/**
 * Whether the encounter is favorited.
 */
isFavorite: boolean }
export type EngineBackend = "cpu" | "vulkan"
export type EngineDevice = { backend: EngineBackend; name: string; type: EngineDeviceType }
export type EngineDeviceType = "cpu" | "discreteGpu" | "integratedGpu" | "accelerator" | "unknown"
export type EngineProbe = { engine: string; protocolVersion: number; sourceCommit: string; buildType: string; variant: string; stub: boolean; compiledBackends: EngineBackend[]; devices: EngineDevice[]; supportedLanguages: VoiceLanguage[] }
export type EngineState = { kind: "missing" } | { kind: "ready"; probe: EngineProbe } | { kind: "incompatible"; reason: string } | { kind: "error"; message: string }
export type FactorCounterTemplate = { itemIds?: number[]; sources?: CounterSource[]; effectSlots?: EffectSlotConfig[] }
export type FineTunedVoiceMeta = { packagePath: string; transformerPath: string; displayName: string; speakerName: string; speakerTokenId: number; modelSha256: string; sizeBytes: number; quantization: string; tokenizerAbi: string; importedAtMs: number }
export type FineTunedVoiceState = { kind: "notConfigured" } | { kind: "ready"; voice: FineTunedVoiceMeta } | { kind: "missing"; voice: FineTunedVoiceMeta } | { kind: "modified"; voice: FineTunedVoiceMeta }
export type GenerationState = { kind: "idle" } | { kind: "running" } | { kind: "cancelling" }
export type GenerationSummary = { completed: number; failed: number; profileId: string | null; assetIds: string[] }
export type GpuSupport = { cuda_available: boolean; opencl_available: boolean }
export type HistoryEntityData = { entityUuid: string; displayUid: number; name: string; classId: number; classSpec: number; className: string; classSpecName: string; abilityScore: number; seasonStrength: number; damage: RawCombatStats; damageBossOnly: RawCombatStats; healing: RawCombatStats; taken: RawCombatStats; dmgSkills: Partial<{ [key in number]: RawSkillStats }>; healSkills: Partial<{ [key in number]: RawSkillStats }>; takenSkills: Partial<{ [key in number]: RawSkillStats }>; takenPerSource: PerSourceStats[]; dmgPerTarget: PerTargetStats[]; healPerTarget: PerTargetStats[]; deaths: DeathRecord[] }
export type I18nRuntimeSnapshot = { locale: AppLocale }
export type LiveRuntimeSnapshot = { eventUpdateRateMs: number }
export type ModelDownloadSource = "auto" | "huggingFace" | "hfMirror"
export type ModelState = { kind: "notInstalled" } | { kind: "installing" } | { kind: "ready"; version: string } | { kind: "corrupt"; version: string; reason: string }
export type ModuleInfo = { name: string; config_id: number; uuid: number; quality: number; parts: ModulePart[] }
export type ModulePart = { id: number; name: string; value: number }
export type ModuleSolution = { modules: ModuleInfo[]; score: number; attr_breakdown: Partial<{ [key in string]: number }> }
export type MonitorRuntimeSnapshot = { i18n: I18nRuntimeSnapshot; live: LiveRuntimeSnapshot; skill: SkillRuntimeSnapshot; monster: MonsterRuntimeSnapshot; teammate: TeammateRuntimeSnapshot; voice: VoiceRuntimeSnapshot }
/**
 * Which caster population a monster-buff voice rule observes.
 */
export type MonsterBuffSourceScope = "anySource" | "localPlayerSource"
export type MonsterRuntimeSnapshot = { enabled: boolean; globalIds: number[]; selfAppliedIds: number[]; monitorAllSelfApplied: boolean }
/**
 * Damage taken by a defender, aggregated by the attacking monster's template.
 */
export type PerSourceStats = {
/**
 * Monster template id of the attacker. None when the source was unknown.
 */
sourceMonsterId: number | null; totalValue: number; taken: RawCombatStats; skills: Partial<{ [key in number]: RawSkillStats }> }
export type PerTargetStats = { targetEntityUuid: string; targetDisplayUid: number; targetMonsterId: number | null; totalValue: number; damage: RawCombatStats; skills: Partial<{ [key in number]: RawSkillStats }> }
/**
 * The result of a query for player names.
 */
export type PlayerNamesResult = {
/**
 * A list of player names.
 */
names: string[] }
/**
 * A summary of a player in an encounter.
 */
export type PlayerSummaryDto = {
/**
 * The player name.
 */
name: string;
/**
 * The class ID of the player.
 */
classId: number }
export type RawCombatStats = { total: number; effectiveTotal: number; hits: number; critHits: number; critTotal: number; luckyHits: number; luckyTotal: number; triggerHits: number; blockHits: number; luckyBlockHits: number }
export type RawSkillStats = { totalValue: number; effectiveTotalValue: number; hits: number; critHits: number; critTotalValue: number; luckyHits: number; luckyTotalValue: number; property: number | null; damageMode: number | null; triggerHits: number; blockHits: number; luckyBlockHits: number }
/**
 * The result of a query for recent encounters.
 */
export type RecentEncountersResult = {
/**
 * The rows of encounter summaries.
 */
rows: EncounterSummaryDto[];
/**
 * The total number of encounters.
 */
totalCount: number }
export type ResetBuffTarget = "selfPlayer" | "anyTeam"
/**
 * The result of a query for scene IDs.
 */
export type SceneIdsResult = {
/**
 * A list of scene IDs.
 */
ids: number[] }
export type SkillRuntimeSnapshot = { enabled: boolean; monitoredSkillIds: number[]; monitoredBuffIds: number[]; monitorAllBuff: boolean; monitoredPanelAttrIds: number[]; buffCounterRules: CounterRule[]; seasonCultivateFactorTemplates: FactorCounterTemplate[] }
export type TeammateRuntimeSnapshot = { enabled: boolean; anySourceIds: number[]; localPlayerSourceIds: number[]; targetSelfSourceIds: number[]; monitorAll: boolean }
export type TickAttrCondition = { attrId: number; requiredValue: number }
/**
 * A single generated take (WAV) for a phrase, using a specific profile/model/params.
 */
export type VoiceAssetMeta = { id: string; phraseId: string; source: VoiceAssetSource; modelVersion: string;
/**
 * Fingerprint of (text, language, profile version, model sha, generation params).
 * Used to detect staleness without storing absolute paths in rules.
 */
paramsFingerprint: string; createdAtMs: number; durationSec: number; sampleRate: number;
/**
 * True when the phrase/profile/model changed after this asset was generated.
 */
stale: boolean }
export type VoiceAssetSource = { kind: "cloneProfile"; profileId: string } | { kind: "fineTuned"; modelSha256: string; speakerName: string; speakerTokenId: number }
export type VoiceBackendInventory = { cpu: VoiceBackendStatus; vulkan: VoiceBackendStatus; recommended: EngineBackend }
export type VoiceBackendStatus = { backend: EngineBackend; engine: EngineState; componentVersion: string | null; updateAvailable: boolean }
/**
 * The full persisted voice catalog (`catalog.json`).
 */
export type VoiceCatalog = { schemaVersion: number; profiles: VoiceProfileMeta[]; phrases: VoicePhraseMeta[]; assets: VoiceAssetMeta[]; installedModelVersion: string | null; installedModelSha256: string | null; fineTunedVoice: FineTunedVoiceMeta | null }
export type VoiceCommandError = { code: string; message: string; retriable: boolean }
export type VoiceGenerateRequestDto = { source: VoiceSourceSelectionDto; phraseIds: string[]; backendPreference?: VoiceGenerationBackend }
export type VoiceGenerationBackend = "auto" | "cpu" | "vulkan"
export type VoiceLanguage = "zhCn" | "enUs" | "jaJp"
export type VoiceOperationState = { kind: "idle" } | { kind: "installingModel"; cancelling: boolean } | { kind: "importingModel" } | { kind: "verifyingModel" } | { kind: "removingModel" } | { kind: "generating"; cancelling: boolean } | { kind: "updatingCatalog" }
/**
 * A fixed phrase (short line) that can be synthesized ahead of time, e.g.
 * "机制来了" / "增益结束".
 */
export type VoicePhraseMeta = { id: string; name: string; text: string; language: VoiceLanguage; activeAssetId: string | null; updatedAtMs: number }
/**
 * A persisted speaker profile (voice clone), backed by a `.q3sp` file on disk.
 */
export type VoiceProfileMeta = { id: string; name: string; createdAtMs: number; modelVersion: string; embeddingDim: number; modelSha256: string; refAudioSha256: string;
/**
 * Whether the original reference WAV was kept on disk (opt-in).
 */
refAudioRetained: boolean }
/**
 * Playback queue policy when the queue is full or a higher priority cue arrives.
 */
export type VoiceQueuePolicy =
/**
 * Drop new low-priority cues when the queue is full.
 */
"dropLowPriority" |
/**
 * Higher priority cues interrupt whatever is currently playing.
 */
"interruptForHigherPriority"
/**
 * A user-defined rule mapping a trigger to a phrase to play.
 */
export type VoiceRule = { id: string; enabled: boolean; trigger: VoiceTrigger; phraseId: string;
/**
 * 0 = lowest, 255 = highest. Higher priority can interrupt lower priority playback.
 */
priority: number; cooldownMs: number;
/**
 * Per-tier phrase variants (fantasy remodel level 0-5), for a
 * `BuffGained`/`BuffLost`/`MonsterBuffGained`/`MonsterBuffLost` rule
 * whose custom text used the `${阶数}` placeholder. When the buff that
 * (un)triggers the rule was applied by a known fantasy summon, its tier
 * selects a variant from this map; falls back to `phrase_id` when the
 * map is absent/empty or has no entry for the observed tier.
 */
phraseIdByTier?: Partial<{ [key in number]: string }> | null }
/**
 * Persisted + hot-synced runtime settings for the voice feature, embedded as
 * a sub-section of `MonitorRuntimeSnapshot` alongside skill/monster/teammate.
 */
export type VoiceRuntimeSnapshot = { enabled: boolean; volume: number; queuePolicy: VoiceQueuePolicy; rules: VoiceRule[] }
export type VoiceSourceSelectionDto = { mode: "cloneNew"; name: string; referenceWavPath: string; keepReference?: boolean } | { mode: "cloneExisting"; profileId: string } | { mode: "fineTuned" }
/**
 * Overall status snapshot returned to the frontend for the voice feature.
 */
export type VoiceStatus = { catalog: VoiceCatalog; model: ModelState; operation: VoiceOperationState; generation: GenerationState; engine: EngineState; backends: VoiceBackendInventory; fineTunedVoice: FineTunedVoiceState }
/**
 * Which real-time game event should trigger a voice cue.
 */
export type VoiceTrigger =
/**
 * The local player gains a buff with this base id.
 */
{ kind: "buffGained"; buffId: number } |
/**
 * The local player loses (all layers of) a buff with this base id.
 */
{ kind: "buffLost"; buffId: number } |
/**
 * The local player's buff with this base id will expire in
 * `seconds_before` seconds (fires once per buff instance).
 */
{ kind: "buffExpiring"; buffId: number; secondsBefore: number } |
/**
 * The current attack target (monster) gains a buff with this base id.
 */
{ kind: "monsterBuffGained"; buffId: number; sourceScope: MonsterBuffSourceScope } |
/**
 * The current attack target (monster) loses (all layers of) a buff
 * with this base id.
 */
{ kind: "monsterBuffLost"; buffId: number; sourceScope: MonsterBuffSourceScope } |
/**
 * The current attack target's buff with this base id will expire in
 * `seconds_before` seconds (fires once per buff instance).
 */
{ kind: "monsterBuffExpiring"; buffId: number; secondsBefore: number; sourceScope: MonsterBuffSourceScope } |
/**
 * A boss "DBM" mechanic world event fires with this base skill id.
 */
{ kind: "bossDbm"; baseSkillId: number } |
/**
 * A boss "DBM" mechanic's timer will expire in `seconds_before` seconds.
 */
{ kind: "bossDbmExpiring"; baseSkillId: number; secondsBefore: number } |
/**
 * A counter rule's slot count reaches its effective threshold.
 */
{ kind: "counterThreshold"; ruleId: number; slotId: number } |
/**
 * A counter rule's slot freeze window will expire in
 * `seconds_before` seconds.
 */
{ kind: "counterExpiring"; ruleId: number; slotId: number; secondsBefore: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
